### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#194]

**Comment by lazaridis-com** [comment]
(the funniest thing of course is that those people have left the project unmaintained, and now the play "big bosses" here. What a joke)

**Comment by ikostenko** [comment]
> Freedom of expression is the foundament of everything, so stop beeing a fascist and censor whatever does not meet your strange criteria of validity.

Freedom of expression does not include the freedom to offence people. And the critreria of validity of any professional discussion are based on respect and politeness.

> the funniest thing of course is that those people have left the project unmaintained, and now the play "big bosses" here.

This project is a volunteering activity, therefore it is maintained when time of the authors permit (all of the authors have full time jobs). 

> Will you please stop locking conversations?

The conversation on #192 was locked in order to stop the heated discussion with usage of offenіsive language. (The fact that you have deleted your comments with words `crap`, `shit`, `sheep`, `fascist`, etc, seems to mean that you understand that such words should not be part of a professional discussion.)

**Comment by jimmyfm** [comment]
@lazaridis-com You cannot call people fascists and then expect to be treated in any other way.

We're all here to contribute, I hope.

@velikanov Said a very interesting thing:
> I think many projects just can not use this because of politics

Which have been buried under petty fights and I really wish to know if the changes on the websites resolved this problem or if further changes are needed.

**Comment by lazaridis-com** [comment]
@ikostenko , i just **react** to your offenses (locking conversations, deleteing comments), and yes,  @jimmyfm , thats how **fascists** work.

The fact that you (ikostenko) continue to talk (logical) **crap** shows your inability to lead a project, both, technically and organizational.

The fact that you still insist on this **invalid** and thus  **moronic** "Made in Ukraine" (FUCKING SHITTY HELL, I'm   G R E E K, and another contributor is R U S S I A N, and another one   WHO KNOWS WHAT NATIONALITY), shows how your minds has gone   SHORTCUTTED   with **crappy** nationalism, which (I repeat) is an **INSULT TO UKRANIAN PEOPLE**.

Yes, you **insult** with your public behaviour your own People.

And I'll use the language which is adequate against **weak fascist minds** which have nothing else to do than censors and block comments.

(And **please**, stop with this off-context crappy whining about "open-source" volunteers etc. - As said, find some sheeps and try to convince them with this nonsense)

If you have even a minimu amount of decency left, **unlock** the conversations, and let the folks decide what to write and what not.

**Comment by lazaridis-com** [comment]
> Which have been buried under petty fights and I really wish to know if the changes on the websites resolved this problem or if further changes are needed.

The Ukranian flag combined with the EU flag is still a problem (clear political message, which can offend mostly south Ukrainian folks and Russian folks, and of course anti-EU anti-West folks).

But the deepest problem with light-adimin is on a technical level (its very difficult, above the currents team ability).

**Comment by jjaksic** [comment]
Lazaridis, you are a troll and an insult to Greeks who, last time I was there, were very nice and polite, unlike yourself.
Why does a flag next to an open source project bother you so much that everyone following this project has to read your rants 15 times a day?
Every goddamn gadget that you use has "Made in China" written on it. So what? How does that make a product any less useful?

Seriously, it's very difficult for someone to volunteer their free time for an open-source project and make it available FOR FREE. You spend A TON of time and get really NOTHING in return. Don't you think letting the lead developer put his country's flag on the project is THE LEAST he can get in return? Don't you think that some gratitude would be appropriate when someone writes most of the code for you, you ungrateful dick?!
Let's make things clear. Max wrote over 400.000 lines of code in this project. You wrote 1.000, and somehow you think you can now boss everyone around? Nope, you don't. When you write 100.000, then you get to pick a flag (or no flag).

Seriously, how stupid do you have to be to go and yell at the person who's writing software FOR YOU FOR FREE? If I were in Max's place, I would at this point seriously consider just dropping the whole thing, because why would someone in their right mind invest so much of their time and effort just to be verbally abused by an idiot like yourself?

Go ahead, create your own open-source project, and after 400.000 lines I'll come and troll until you drop. See how you like it.

**Comment by ikostenko** [comment]
> *lazaridis-com:* And I'll use the language which is adequate against weak fascist minds which have nothing else to do than censors and block comments.

@lazaridis-com 
We did not censor (delete) the comments that you have already added.
As seen from the below comparison of yesterday's screenshot of #192 discussion, and today's screenshot, **you have deleted all your comments to #192 yourself, and asked others to do so**

Yesterday the discussion looked like this:
![image](https://cloud.githubusercontent.com/assets/2362119/7669688/d5b94b86-fc89-11e4-95ef-bd98e9a7a6a9.png)

Today it looks like this:
![image](https://cloud.githubusercontent.com/assets/2362119/7669685/cef08e2c-fc89-11e4-8649-7a2e5ec8515e.png)

@velikanov 
 > I think many projects just can not use this because of politics

Could you please clarify if there is anything else we can do to resolve the issue you have described?

**Comment by lazaridis-com** [comment]
Let's bake a cake and make peace! (I start again to delete my messages, as I do sometimes, whe **censorship** is applied, either by deletion or by blockage).

**Comment by lazaridis-com** [comment]
@jjaksic , I didn't read your message. Can you (or someone else) can look into this one:

lazaridis-com/light-admin#10

I cannot go into code-level work at this time, and this seems to be the last issue towards the need update to spring-platform usage.

**Comment by lazaridis-com** [comment]
USERS OF OPEN SOURCE RISE UP!!!   Y O U   ARE OPEN SOURCE, NOT THE WRITERS!

**Comment by lazaridis-com** [comment]
Please add a banner to the project page: "We Want Free Pizza"

**Comment by max-dev** [comment]
Just opened my laptop. I didn't expect he is still wasting your time, mates. @jjaksic @jimmyfm @ikostenko Thanks for your support anyway)
@jimmyfm Agree with you & thanks to @velikanov for raising this point. Looking forward to hear from him. 
To be honest, it was a BIG surprise that something like that should be considered in FREE/OSS at all.

@lazaridis-com Removing comments... Renaming topics? Really? You're just a dirty coward/troll hiding behind the safety screen.

**Comment by lazaridis-com** [comment]
@max-dev , I'm just **categories** more professional than you will ever get. That's all it is.
