### ISSUE TITLE
[URGENT] Call for Tests

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#202]
( @max-dev , stay away from this issue, thus users see it. You care about your users, don't you? )

On my side, the test-system makes problems (it does not connect to firefox).

Can you please test on your side, using this sequence:

checkout latest master

complie and test in one chunk, with automaticly started jetty (from the root of the project)

```
mvn clean install integration-test -Pdev-mode
```

The same tests should the be made with an earlier version (the last version prior to me starting send changes in)

```
git checkout 219a7ea
mvn clean install integration-test -Pdev-mode
```

and finally with the 1.0.1.RELEASE (lightadmin-sandbox was lightadmin-demo)

```
git checkout 1.0.1.RELEASE
mvn clean install integration-test -Pdev-mode
```

-

An alternative way is to to test with manually started tomcat

```
cd lightadmin-sandbox
mvn tomcat7:run
(in another shell)
cd lightadmin-tests
mvn integration-test -Ptest-mode
```

.

**Comment by ikostenko** [comment]
@lazaridis-com Thank you for the detailed description of the issue.
This issue was indeed reproducible on my side
As far as I can see, this is because the Selenium v. 2.32.0 does not support the updated version of Firefox (which often happens when Firefox updates). I have just pushed `pom.xml` of `lightadmin-test` module with the updated Selenium version which makes it possible to run the UI tests.
@lazaridis-com Could you please check if this solves your issue? (At the moment, I cannot verify this because I am at work. I'll be able to take a closer look in the evening today) 

I was hesitant to push Selenium version update after the latest pull request merge due to several reasons: 
1. @akurdyukov updated the sources of the tests in his commit https://github.com/lazaridis-com/light-admin/commit/52789132e24f175c516f2f2b8b5e773d0374a8b8 , so it seems like he _managed to start the tests_ to verify the test sources updates and *might be working on an update of Selenium version*. 
2. Even after updating the version of Selenium locally (at my PC), many tests failed, and it seems like @akurdyukov is working on updates of the tests or is investigating the causes of the failure.

@akurdyukov please let me know if there is anything I can help you in investigating or fixing these tests

**Comment by ikostenko** [comment]
@lazaridis-com 
We kindly ask you **not to take the delays with the answers or the answers themselves personally**, as we do not have any intention to offend any of the **contributors one of which you certainly are**.

The reason of the delays is (as I mentioned previously) that all of the project authors have full time jobs at which **we for a long time now have a high workload due to planned releases**

The fact that you use strong offensive language when communicating with people who _intensively contributed their efforts and spare time_ into a **free open source** project (source code, tests, documentation, website) _for about 1,5 years before the users started appreciating it_, does not create the atmosphere of trust and creativity. However, we are doing our best to perceive your activity as an evidence that LightAdmin is indeed used and appreciated by the users. 

Best regards,
Iryna Kostenko

**Comment by lazaridis-com** [comment]
( @ikostenko , I'm not writing to you here, I'm writing to the **users** which should not suffer under an incapable project-lead who's obviously blinded by his ego).

As already said: if you want to talk like this (twisting facts, typical open-source-whining), then go find some sheeps to talk to - not me. And you should think about starting a carreer in politics.

I had already updated the selenium version on my side, just wanted to be sure that the default test-system is **non-functional**. Tell it to your big master, which asks for tests, without having a stable test-system (see #197), blocking PR's whilst playing either smart or dumb - depending what fits the situation.

As for debugging, this is naturally something that the original author of the code should do (once he overcomes his giant ego to merge PR's, either into master or into a brach).

**Comment by lazaridis-com** [comment]
Well, users, it can't get any more sicker.

I've tested some versions, they **all** have problems (some tests fail). So, the **Master** here rejected my PR, because I was a bad boy, and I did not run the tests, but the reality of this project is:

* The test-system itself is not stable
* The tests fail, even with stable versions (independent of my changes).

Can it get any sicker?

**Comment by max-dev** [comment]
@lazaridis-com Good try, but the test framework is stable enough to make tests green.

I would suggest you to find another place for your 'contributions' & stop spamming.

**Comment by lazaridis-com** [comment]
The only person spamming on this project is you, by your redundant comments and missing actions (e.g. merging #204, at least to a new branch, thus users following this project can test without hassle).

Note to readers: a professional would now ask for the test-logs, in order to determine the cause of the problems. It is important that you realize that this project is a dead-end - it will **never** reach completeness and maturity.

**Comment by lrkwz** [comment]
I run the tests as asked in #198: Some Selenium test fail for me on master branch (61803b27e3e7850c13576fbb7452eb35f32b6a6e).

This is a small interesting time saving project I wish to thank the maintainer and ALL the contributors; please @lazaridis-com calm down: your help is formidable but please respect ALL the other developers.

**Comment by lazaridis-com** [comment]
@lrkwz , to be blunt: You have the right to be delusional, but please, **fuck off** with your clearly biased comments subject "respect".

**Comment by lazaridis-com** [comment]
As for the tests (the main topic here), have you tried with the earlier versions?

```
git checkout 219a7ea
mvn clean install integration-test -Pdev-mode
```

and

```
git checkout 1.0.1.RELEASE
mvn clean install integration-test -Pdev-mode
```

**Comment by lazaridis-com** [comment]
Update: I've isolated one problem-cause in the test-system: -Pdev-mode uses jetty8, which introduces some problems. Use the -Ptest-mode (launch sandbox example, then start tests). Latest result on my side:

with selenium 2.45.0 and chrome 42.0.2311.152 m

https://github.com/lazaridis-com/light-admin/commit/56bd1c104a64219dc65ed9d9bb17bb0c79d2c7d4 `Tests run: 54, Failures: 3, Errors: 7, Skipped: 3`

-

Now, believe it or not, but the original developer, **incapable** to admit his failure, sucks out **my** and the **users** energy, and now calls me a... "spammer"!

> I would suggest you to find another place for your 'contributions' & stop spamming.

So, this here #204 is spam, and that's why it does not get merged (thus testing becomes simpler).

How can a person show so much disrespect to itself? But most possibly, this explains why even the original team has left (https://github.com/la-team - home alone).

(just wondering why "Master of the Buttons" does not block me on his repo, so he's again totally alone)

**Comment by lazaridis-com** [comment]
@max-dev , do you actually realize that you **spit into the faces** of your **users**, when closing issues like that? It is one thing to **fail** with open-source software, it is another thing to **block** efforts of others to cover for your failures. No wonder the team left you alone.

(btw., as you like closing issues, why not close this one: #166?

-

Repeating deleted message:

@lrkwz  , to be blunt: You have the right to be delusional, but please, fuck off with your clearly biased comments subject "respect".

-

Repeating deleted message:

Update: I've isolated one problem-cause in the test-system: -Pdev-mode uses jetty8, which introduces some problems. Use the -Ptest-mode (launch san…

(forgot what I had written)
